src/Entity/Pizza.php
<?php

namespace App\Entity;

use App\Repository\PizzaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: PizzaRepository::class)]
#[Vich\Uploadable]
class Pizza
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Vich\UploadableField(mapping: 'pizza', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Assert\NotNull()]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Assert\NotNull()]
    private \DateTimeImmutable $updatedAt;

    #[ORM\ManyToMany(targetEntity: Ingredient::class)]
    private Collection $ingredients;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable;
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients->add($ingredient);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        $this->ingredients->removeElement($ingredient);

        return $this;
    }

    public function getPrice(): ?float
    {
        $prices = 0;
        foreach ($this->getIngredients() as $ingredient) {
            $prices = $prices + $ingredient->getPrice();

        }
        return $prices;
    }

    public function getIngredientsIds(): ?array
    {
        $ids = [];
        foreach ($this->getIngredients() as $ingredient) {
            $ids[] = $ingredient->getId();
        }
        return $ids;
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Repository\PizzaRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class ClientController extends AbstractController
{

    #[Route('/', name: 'app_client_public')]
    /**
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_CLIENT')")
     */
    public function espace(
        PizzaRepository    $pizzaRepository,
        PaginatorInterface $paginator,
        Request $request): Response
    {
        $pizzas = $pizzaRepository->findAll();
        return $this->render('client/index.html.twig', [
            'pizzas' => $pizzas
        ]);
    }

    #[Route('/commande', name: 'app_commande')]
    /**
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_CLIENT')")
     */
    public function commande(): Response
    {
        return $this->render('client/commande.html.twig');
    }
}

templates/client/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande en cours de Prépration{% endblock %}

{% block body %}
    <div class="container">
        <main>
            <div class="container py-4">
                <header class="pb-3 mb-4 border-bottom">
                    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                        <span class="fs-4">Commande En cours de Préparation</span>
                    </a>
                </header>

                <div class="p-5 mb-4 bg-light rounded-3">
                    <div class="container-fluid py-5">
                        <h1 class="display-5 fw-bold">Merci pour votre patience</h1>
                        <p class="col-md-8 fs-4">The best Pizza </p>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}The best Pizza Site{% endblock %}

{% block body %}
    <div class="container">
        <section style="background-color: #eee;">
            <div class="text-center container py-5">
                <h4 class="mt-4 mb-5"><strong>Nos Pizzas</strong></h4>
                <div class="row">
                    {% for pizza in pizzas %}
                        <div class="col-lg-4 col-md-12 mb-4">
                            <div class="card">
                                {% if hasAllergicIngredient(app.user, pizza.id) == true  %}
                                    <h7 class="text-danger">Cette pizza contient des ingrédients dont vous êtes allergiques !</h7>
                                {% endif %}
                                <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                                     data-mdb-ripple-color="light">
                                    {% if vich_uploader_asset(pizza, 'imageFile') is not null %}
                                        <img src="{{ vich_uploader_asset(pizza, 'imageFile') }}"
                                             class="w-100" height="400px"/>
                                    {% else %}
                                        <img src="{{ asset('images/coming-soon-header.jpg') }}"
                                             class="w-100"/>
                                    {% endif %}
                                    <a href="{{ path('app_commande') }}">
                                        <div class="mask">
                                            {% for ingredient in pizza.ingredients %}
                                                <div class="d-flex justify-content-start align-items-end h-100">
                                                    <h5>
                                                        {% if isAllergic(app.user, ingredient.id) == true %}
                                                            <span class="badge bg-danger ms-2">{{ ingredient.name }}</span>
                                                        {% else %}
                                                            <span class="badge bg-primary ms-2">{{ ingredient.name }}</span>
                                                        {% endif %}
                                                    </h5>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="hover-overlay">
                                            <div class="mask"
                                                 style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                        </div>
                                    </a>
                                </div>
                                <div class="card-body">
                                    <a href="{{ path('app_commande') }}" class="text-reset">
                                        <h5 class="card-title mb-3">{{ pizza.name }}</h5>
                                    </a>
                                    {% if pizza.price %}
                                        <h6 class="mb-3">Prix (en €) :{{ pizza.price }}</h6>
                                    {% else %}
                                        <h6 class="mb-3">Prix non renseigné</h6>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </section>
    </div>
{% endblock %}